version: '3'

services:

  server:
    image: homebrew/brew:latest
    # command: server # if you want a live server. idk where that /public folder is. idk why theme isn't there
    # entrypoint: hugo-official
    # environment:
    #   - HUGO_DESTINATION_ARG=/public
    volumes:
      - "./:/app"
    ports:
      - "1313:1313"

networks:
  quartz-dnd-network:
    driver: bridge